# Generated by Django 3.0.5 on 2020-05-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(auto_created=True, max_length=8, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('typeid', models.AutoField(auto_created=True, max_length=8, primary_key=True, serialize=False, verbose_name='商品类型ID')),
                ('typename', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'ItemType',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(max_length=8, primary_key=True, serialize=False, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '已发货'), (3, '已完成'), (4, '已取消'), (5, '已退款'), (6, '已退货')], verbose_name='订单状态')),
                ('delivery_company', models.CharField(blank=True, max_length=8, null=True, verbose_name='物流公司')),
                ('delivery_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='快递单号')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=8, verbose_name='商品ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买单价')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('item_id', models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.Item', verbose_name='商品ID')),
                ('inventory', models.IntegerField(verbose_name='库存量')),
            ],
            options={
                'verbose_name': '库存信息',
                'verbose_name_plural': '库存信息',
                'db_table': 'StockInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.Account', verbose_name='账户')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='昵称')),
                ('sex', models.BooleanField(choices=[(True, '男'), (False, '女')], verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='绑定手机')),
                ('register_date', models.DateField(auto_now_add=True, null=True, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('review_id', models.AutoField(auto_created=True, max_length=8, primary_key=True, serialize=False, verbose_name='评价ID')),
                ('review_property', models.IntegerField(choices=[(0, '差评'), (1, '中评'), (2, '好评')], default=3, verbose_name='评价属性')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('order_id', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='shop.OrderDetails', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'ProductReview',
            },
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_review',
            field=models.OneToOneField(blank=True, db_column='pr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductReview', verbose_name='评价ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='typeid',
            field=models.ForeignKey(db_column='typeid', on_delete=django.db.models.deletion.PROTECT, to='shop.ItemType', verbose_name='商品类型ID'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('order_id', 'item_id')},
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.UserInfo', verbose_name='账户'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addr_id', models.AutoField(auto_created=True, max_length=8, primary_key=True, serialize=False, verbose_name='地址ID')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('address', models.CharField(max_length=50, verbose_name='收货地址')),
                ('phone_number', models.CharField(max_length=15, verbose_name='联系电话')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='shop.UserInfo', verbose_name='账户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='商品ID')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='shop.UserInfo', verbose_name='账户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'Cart',
                'unique_together': {('item_id', 'username')},
            },
        ),
    ]
