# Generated by Django 3.0.5 on 2020-05-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='address',
            name='addr_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='地址ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='typeid',
            field=models.ForeignKey(db_column='typeid', on_delete=django.db.models.deletion.PROTECT, to='shop.ItemType', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='typeid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='商品类型ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='评价ID'),
        ),
    ]
