# Generated by Django 3.0.5 on 2020-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200507_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '已发货'), (3, '已完成'), (4, '已取消'), (5, '已退款'), (6, '已退货')], default=0, verbose_name='订单状态'),
        ),
    ]
