# Generated by Django 3.0.5 on 2020-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200509_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summary_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额'),
        ),
    ]
